// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4ROleFxFHnAFT5G-SZKAhZOeyXVsbOv8',
    appId: '1:404040605377:web:cb0a87b4fb56c34e1f3e40',
    messagingSenderId: '404040605377',
    projectId: 'flutter-montra',
    authDomain: 'flutter-montra.firebaseapp.com',
    storageBucket: 'flutter-montra.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmo_rlJ3bwnU_ahRUGpCK4ioLQ85h0Vac',
    appId: '1:404040605377:android:df84e6dc66409f9e1f3e40',
    messagingSenderId: '404040605377',
    projectId: 'flutter-montra',
    storageBucket: 'flutter-montra.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7PBXWXxvjnKrdWTmvkJNPy1ExRgacsZc',
    appId: '1:404040605377:ios:2ded0fc72c39a6db1f3e40',
    messagingSenderId: '404040605377',
    projectId: 'flutter-montra',
    storageBucket: 'flutter-montra.appspot.com',
    iosClientId: '404040605377-2ugs1t1ilt084ltl0d9h1me9efr3u537.apps.googleusercontent.com',
    iosBundleId: 'com.nevertell.montra',
  );
}
